field: 67c7c51f-2f9c-4a68-bdcb-41ffdb733a15 # Header Content
fieldLayouts:
  c4b01c80-d51a-467e-b857-246adf1d27d7:
    tabs:
      -
        elements:
          -
            fieldUid: a16de839-7980-475d-9aff-87edc71a4f1d # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c0a0afd6-a747-4319-9886-634a67f336a2 # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 8b684cd5-4788-4c88-8f90-9ac9337489d5 # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: d5127b50-8800-45cd-aa23-8c9302111cb0 # Button Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  8b684cd5-4788-4c88-8f90-9ac9337489d5: # Button Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonStyle
    instructions: ''
    name: 'Button Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Ghost
            -
              - value
              - ghost
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a16de839-7980-475d-9aff-87edc71a4f1d: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        3: entry
        6: custom
        7: email
        8: tel
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: 'Read More'
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  c0a0afd6-a747-4319-9886-634a67f336a2: # Width
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: width
    instructions: ''
    name: Width
    searchable: false
    settings:
      decimals: 0
      defaultValue: 10
      max: null
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  d5127b50-8800-45cd-aa23-8c9302111cb0: # Button Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonColour
    instructions: ''
    name: 'Button Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Master
            -
              - value
              - master
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Inherit
            -
              - value
              - inherit
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: ctaBlock
name: 'CTA Block'
sortOrder: 3
