field: 7308fede-1fa5-44c4-9ef0-c470e247147e # Blocks
fieldLayouts:
  0d905282-cda1-4b9d-b82c-6bb9204794df:
    tabs:
      -
        elements:
          -
            fieldUid: f4c3a92b-10af-4dbd-8c25-577563971125 # Block Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 741b1640-f59f-4406-a05b-4752602c84fd # Block Padding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 13dd320c-9252-4a1c-b401-271cf7e9667d # Embed Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  13dd320c-9252-4a1c-b401-271cf7e9667d: # Embed Code
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: embedCode
    instructions: ''
    name: 'Embed Code'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  741b1640-f59f-4406-a05b-4752602c84fd: # Block Padding
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockPadding
    instructions: ''
    name: 'Block Padding'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Padding Top'
                -
                  - handle
                  - paddingTop
                -
                  - width
                  - ''
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - None
                        -
                          - value
                          - pad-top-000
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'XX Small'
                        -
                          - value
                          - pad-top-100
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'X Small'
                        -
                          - value
                          - pad-top-200
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Small
                        -
                          - value
                          - pad-top-300
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Medium
                        -
                          - value
                          - pad-top-400
                        -
                          - default
                          - true
                    -
                      __assoc__:
                        -
                          - label
                          - Large
                        -
                          - value
                          - pad-top-500
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'X Large'
                        -
                          - value
                          - pad-top-600
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'XX Large'
                        -
                          - value
                          - pad-top-700
                        -
                          - default
                          - false
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Padding Bottom'
                -
                  - handle
                  - paddingBottom
                -
                  - width
                  - ''
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - None
                        -
                          - value
                          - pad-top-000
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'XX Small'
                        -
                          - value
                          - pad-top-100
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'X Small'
                        -
                          - value
                          - pad-top-200
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Small
                        -
                          - value
                          - pad-top-300
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Medium
                        -
                          - value
                          - pad-top-400
                        -
                          - default
                          - true
                    -
                      __assoc__:
                        -
                          - label
                          - Large
                        -
                          - value
                          - pad-top-500
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'X Large'
                        -
                          - value
                          - pad-top-600
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'XX Large'
                        -
                          - value
                          - pad-top-700
                        -
                          - default
                          - false
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'Padding Left'
                -
                  - handle
                  - paddingLeft
                -
                  - width
                  - ''
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - None
                        -
                          - value
                          - pad-top-000
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'XX Small'
                        -
                          - value
                          - pad-top-100
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'X Small'
                        -
                          - value
                          - pad-top-200
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Small
                        -
                          - value
                          - pad-top-300
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Medium
                        -
                          - value
                          - pad-top-400
                        -
                          - default
                          - true
                    -
                      __assoc__:
                        -
                          - label
                          - Large
                        -
                          - value
                          - pad-top-500
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'X Large'
                        -
                          - value
                          - pad-top-600
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'XX Large'
                        -
                          - value
                          - pad-top-700
                        -
                          - default
                          - false
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - 'Padding Right'
                -
                  - handle
                  - paddingRight
                -
                  - width
                  - ''
                -
                  - type
                  - select
                -
                  - options
                  -
                    -
                      __assoc__:
                        -
                          - label
                          - None
                        -
                          - value
                          - pad-top-000
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'XX Small'
                        -
                          - value
                          - pad-top-100
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'X Small'
                        -
                          - value
                          - pad-top-200
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Small
                        -
                          - value
                          - pad-top-300
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - Medium
                        -
                          - value
                          - pad-top-400
                        -
                          - default
                          - true
                    -
                      __assoc__:
                        -
                          - label
                          - Large
                        -
                          - value
                          - pad-top-500
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'X Large'
                        -
                          - value
                          - pad-top-600
                        -
                          - default
                          - false
                    -
                      __assoc__:
                        -
                          - label
                          - 'XX Large'
                        -
                          - value
                          - pad-top-700
                        -
                          - default
                          - false
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  f4c3a92b-10af-4dbd-8c25-577563971125: # Block Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockColour
    instructions: ''
    name: 'Block Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - 'bg-light-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - 'bg-dark-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - 'bg-primary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - 'bg-secondary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - 'bg-tertiary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - 'bg-quaternary-main pad-400'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: embed
name: Embed
sortOrder: 15
