field: 7308fede-1fa5-44c4-9ef0-c470e247147e # Blocks
fieldLayouts:
  7f373a9f-2e54-4a0d-8991-9b7fe15ca6dc:
    tabs:
      -
        elements:
          -
            fieldUid: 21752b07-7e86-47b8-bb8d-900b25831dd4 # Block Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: f1313852-90e0-4c0c-8dd9-c7a2c7b45582 # UI Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 014df9d2-eed4-4979-b839-6dded10d5345 # Accordion Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 992267ad-23ed-4224-9d16-d27e48b84211 # Active UI Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: d4c3ee53-e5fb-4e90-b020-551c86e412ce # Active Accordion Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 676fc6db-775f-449d-863c-891672b77678 # FAQ
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  014df9d2-eed4-4979-b839-6dded10d5345: # Accordion Background
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: accordionBackground
    instructions: ''
    name: 'Accordion Background'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  676fc6db-775f-449d-863c-891672b77678: # FAQ
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: faq
    instructions: ''
    name: FAQ
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  21752b07-7e86-47b8-bb8d-900b25831dd4: # Block Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockColour
    instructions: ''
    name: 'Block Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - 'bg-light-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - 'bg-dark-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - 'bg-primary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - 'bg-secondary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - 'bg-tertiary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - 'bg-quaternary-main pad-400'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  992267ad-23ed-4224-9d16-d27e48b84211: # Active UI Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: activeUiColour
    instructions: ''
    name: 'Active UI Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - color-light-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - 'color-dark-open dark-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - 'color-primary-open primary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - 'color-secondary-open secondary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - 'color-tertiary-open tertiary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - 'color-quaternary-open quaternary-main'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  d4c3ee53-e5fb-4e90-b020-551c86e412ce: # Active Accordion Background
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: activeAccordionBackground
    instructions: ''
    name: 'Active Accordion Background'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-open
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f1313852-90e0-4c0c-8dd9-c7a2c7b45582: # UI Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: uiColour
    instructions: ''
    name: 'UI Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - 'color-light-main  border-light-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - 'color-dark-main border-dark-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - 'color-primary-main border-primary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - 'color-secondary-main border-secondary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - 'color-tertiary-main border-tertiary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - 'color-quaternary-main border-quaternary-main'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: faq
name: FAQ
sortOrder: 16
