field: 44ebe5b2-8f14-48b9-a466-427f7b21a552 # Hero Block
fieldLayouts:
  3fe70794-b112-4dee-a99f-6cac2988dd77:
    tabs:
      -
        elements:
          -
            fieldUid: 570a2608-a597-432b-b6cb-ed376f474a67 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 0300c41d-da59-4344-8ba9-821e00f30a78 # Image Crop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 64ebd5cd-c100-44bd-87e1-3aac2280e7d5 # Image Fit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  64ebd5cd-c100-44bd-87e1-3aac2280e7d5: # Image Fit
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageFit
    instructions: ''
    name: 'Image Fit'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Stretch
            -
              - value
              - stretch
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Top Left'
            -
              - value
              - topLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Top Right'
            -
              - value
              - topRight
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Left'
            -
              - value
              - bottomLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Right'
            -
              - value
              - bottomRight
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Centre Right'
            -
              - value
              - centreRight
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Centre Left'
            -
              - value
              - centreLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Centre Centre'
            -
              - value
              - centreCentre
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  0300c41d-da59-4344-8ba9-821e00f30a78: # Image Crop
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageCrop
    instructions: ''
    name: 'Image Crop'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Original
            -
              - value
              - original
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '4:3'
            -
              - value
              - fourThree
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16:9'
            -
              - value
              - medium
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  570a2608-a597-432b-b6cb-ed376f474a67: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageAsset
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:abfe2548-e0eb-46f4-b4f8-b5a54a315752' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: thumbs
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:abfe2548-e0eb-46f4-b4f8-b5a54a315752' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
