field: 7308fede-1fa5-44c4-9ef0-c470e247147e # Blocks
fieldLayouts:
  3c46421c-5111-497c-859a-bb0ee2aa5bb7:
    tabs:
      -
        elements:
          -
            fieldUid: 0f1dc88f-9a14-448e-b00c-9e03b2b04f10 # Block Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 89cf70c5-c1ae-4511-9a19-45e4390223fd # Orientation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: bd92bbd3-73fa-4d9b-9cfd-85060520085e # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 6977bf2a-4f86-4392-921c-2a68f25f53a8 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0f1dc88f-9a14-448e-b00c-9e03b2b04f10: # Block Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockColour
    instructions: 'Set block background colour'
    name: 'Block Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - 'bg-light-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - 'bg-dark-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - 'bg-primary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - 'bg-secondary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - 'bg-tertiary-main pad-400'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - 'bg-quaternary-main pad-400'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  89cf70c5-c1ae-4511-9a19-45e4390223fd: # Orientation
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: orientation
    instructions: 'Set block oreintation'
    name: Orientation
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Stretch
            -
              - value
              - stretch
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Top Left'
            -
              - value
              - topLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Top Centre'
            -
              - value
              - topCentre
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Top RIght'
            -
              - value
              - topRight
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Centre Left'
            -
              - value
              - centreLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Centre Centre'
            -
              - value
              - centreCentre
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Centre Right'
            -
              - value
              - centreRight
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Left'
            -
              - value
              - bottomLeft
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Centre'
            -
              - value
              - bottomCentre
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Right'
            -
              - value
              - bottomRight
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  6977bf2a-4f86-4392-921c-2a68f25f53a8: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: ''
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - json
        - video
      defaultUploadLocationSource: 'volume:abfe2548-e0eb-46f4-b4f8-b5a54a315752' # Uploads
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:abfe2548-e0eb-46f4-b4f8-b5a54a315752' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bd92bbd3-73fa-4d9b-9cfd-85060520085e: # Thumbnail
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: thumbnail
    instructions: ''
    name: Thumbnail
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:abfe2548-e0eb-46f4-b4f8-b5a54a315752' # Uploads
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:abfe2548-e0eb-46f4-b4f8-b5a54a315752' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: videoBlock
name: Video
sortOrder: 3
