fieldLayouts:
  e11d1720-1881-4628-a091-05b7c470353e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 65028693-f2c1-4a3f-bee7-71370c96cbe2 # Area
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c23d3217-1a4e-4309-8e52-98b45ba77d6e # Attraction Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b28aae5d-6a5a-4deb-a915-960b43c78b3a # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2a3094f-ad30-447b-993d-a365b5568512 # Address 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a3685719-5b26-4782-8b39-d35a14a118af # Town
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 44b4e433-f3d7-46d1-9431-8bad91fd474d # County
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3511cd3f-4c9b-4cf4-80b9-8baf5444f1b3 # Postcode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 21198b4a-e809-4100-be79-44ed3e8e5850 # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 182cf075-1284-45ed-87d2-7ffd098d689d # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 818249db-74e9-450e-93c2-9669736aba11 # Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8ef917b-104a-4fdf-a1ba-69e2a88dac4a # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3fb12f6d-48c7-46c8-967e-2cb2ca50e94b # Twitter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f5a3ef2-7473-4fa0-a7e7-88e9aef50f38 # Instagram
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 34cff7da-e728-48a8-b60b-70c76600c322 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eae5ab77-d16b-42ca-a4fe-474054102b46 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 867a0597-b673-491d-a171-9ed07641318d # Top 100 Review
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 80cc27cc-c229-4d77-aa18-a29ff3a8c63a # Tiqets Embed Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c79aa329-c7d7-4eaf-8dec-2131e6ba0552 # Trip Advisor Embed Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0c3a3cd8-b068-4302-98f1-9da2ca699354 # Video Embed Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b590e52-4409-4491-821c-b5fe3354606a # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e13473b1-dbbc-4296-bfa1-dce8dc0440f1 # Attraction Image Crop Mode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0420fc8d-7a34-4ed3-8db0-e93596db2c3b # Attraction Image Focal Point
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bd76c6b6-b987-4345-bf81-2cfb7dca5c9e # Attraction Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 47b229ab-bbd9-4d26-9ef3-97b7bacf2718 # Related Attractions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6fa94078-b67a-4d62-afd1-97a30d438f71 # Exclude Attractions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ed2a853a-010f-4fef-8c46-0bec4a05c415 # Order Priority
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e00f8d4a-ee39-4663-b538-a0ecbd9af1e3 # App
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e7aba3d9-1c11-4926-bae2-bd3684df92ea # Booking.com Affiliate Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 544bd40f-7b2c-4945-b564-2c76618983fd # Featured
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 625286fd-f221-4e9f-9233-f8a025dfb1ca # National Trust Member
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae0a9e42-83e4-47e9-9636-5384df2ea381 # Photos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d622e54f-2208-47a6-b5f5-70628b083487 # Old Site Id
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ebf7a9f8-2506-4212-9ab9-b47c66f9e807 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ae2014b-9fdf-4d09-977e-03d2a8b9795d # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: attractions
hasTitleField: true
name: Attractions
section: 305f3d85-db06-447d-8f4b-3cbad76f8456 # Attractions
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
