fieldLayouts:
  bd81543e-e2f7-42fc-8865-e89de477e97a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: Question
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 4ae2014b-9fdf-4d09-977e-03d2a8b9795d # Excerpt
            instructions: ''
            label: Answer
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: faq
hasTitleField: true
name: FAQ
section: 4f993a86-31b6-4bd2-9a02-15b22639b252 # FAQ
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
