fieldLayouts:
  c53ce68e-c7ab-4beb-bc84-3e6248a927ed:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 8a590f78-5665-4cd9-8319-23d44655c436 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: a70e2e58-f8b7-4161-86bc-d854cb907a0e # Hero Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 43ac81ba-f40e-4bb9-9d46-10d4a8929776 # Attraction Form Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 07429935-85d1-4db8-9d26-dc7f10288711 # In Header Attraction Form Title
            instructions: 'If left blank, the text from Globals > Attractions, will be used.'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 691ace41-89cf-4772-bce2-8abf60517287 # Attractions Form Label
            instructions: 'If left blank, the text from Globals > Attractions, will be used.'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 2
      -
        elements:
          -
            fieldUid: b74c2ea3-c134-4b37-ab0d-b341a539085b # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 4ae2014b-9fdf-4d09-977e-03d2a8b9795d # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 961df376-6fa9-4b26-b1c6-ade1f716d7eb # SEO Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Meta'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 0e8f11a4-ce20-4477-b9a4-86c5dac225dc # Header Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 7db1b0f1-4f1f-4a0c-a135-08e6014e7582 # Header Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: ebf7a9f8-2506-4212-9ab9-b47c66f9e807 # Logo
            instructions: ''
            label: 'Alternative Logo'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 58420e26-1c78-4017-a65e-c041d47c974f # Colours
            instructions: ''
            label: 'Colour Overides'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb9cfd6f-b8eb-45cf-a0bb-cb2fdf62d6b9 # Password Protected
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Theme'
        sortOrder: 4
handle: home
hasTitleField: true
name: Home
section: 84c87475-bc39-4237-9bd4-a4302e95d9a7 # Home
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
