fieldLayouts:
  e8aeeaaa-9433-46e1-a985-bd7e30b6bbb6:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 871c9ea9-13cc-4937-be65-0b2af3a80a12 # Text
            instructions: ''
            label: Caption
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 602986fb-25c4-4302-b1ea-4871ab358a76 # Plain Text
            instructions: ''
            label: 'Alt Text'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: uploads
hasUrls: true
name: Uploads
settings:
  path: '@webroot/uploads'
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@web/uploads'
