columnSuffix: null
contentColumnType: text
fieldGroup: f0ef98a7-7413-48ac-9895-e10ca314be4b # App
handle: app_security
instructions: ''
name: 'Security Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
