columnSuffix: null
contentColumnType: string
fieldGroup: 1b7fc8a8-249a-4fc5-b47c-24fe458aba9f # Attractions
handle: attraction_area
instructions: ''
name: Area
searchable: false
settings:
  allowSelfRelations: false
  limit: '5'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:5e5419a1-45e5-45fb-a2d4-d971bc6b9b9f' # Areas
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
