columnSuffix: suappcgc
contentColumnType: text
fieldGroup: 1b7fc8a8-249a-4fc5-b47c-24fe458aba9f # Attractions
handle: attractionsFormLabel
instructions: ''
name: 'Attractions Form Label'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
