columnSuffix: null
contentColumnType: string
fieldGroup: af775646-00cc-418c-8deb-b1a621f2126f # Blog Posts
handle: category
instructions: ''
name: Category
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:6a9714b4-95da-4d98-9b38-83ce096df9ad' # Category
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
