columnSuffix: null
contentColumnType: string
fieldGroup: fe73f07f-bb89-49f8-887c-958a2abf069d # Common
handle: navigation
instructions: ''
name: Navigation
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigation}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
