columnSuffix: null
contentColumnType: string
fieldGroup: af775646-00cc-418c-8deb-b1a621f2126f # Blog Posts
handle: passwordProtected
instructions: ''
name: 'Password Protected'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - b17810a9-0a78-4de6-820b-b8cf00ac3864 # Password
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_passwordprotected}}'
  fieldLayout: table
  maxRows: '1'
  minRows: '0'
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add Password to Page'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
