columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 7c4961a4-381e-494b-b2dd-bf0b6a8c1898 # Area
handle: radius
instructions: ''
name: Radius
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
