columnSuffix: null
contentColumnType: text
fieldGroup: af775646-00cc-418c-8deb-b1a621f2126f # Blog Posts
handle: stylesheet
instructions: 'Enter CSS code here. Entered into <head> insides <style>'
name: Stylesheet
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '10'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
