columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 09de7142-9c26-4492-b60a-b69534ef671a # Fonts
handle: testimonialLimit
instructions: ''
name: 'Testimonial Limit'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
