field: c2ec863d-1c2e-47a4-a928-1d6d54b3989f # Blog Intro
fieldLayouts:
  025ce23c-4204-4fb7-a6bc-05e6b47f3adb:
    tabs:
      -
        elements:
          -
            fieldUid: 57d7fb75-9f65-4cb3-8af1-872b184c442c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d745e29-a2e8-47b5-a584-510330af7397 # Sidebar Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 58ac5a7f-03a6-4058-a3ea-97165e94a9fe # Sidebar Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ef9f9772-7ef7-46f7-bbd0-7a557f0231a5 # Text Area
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c1a37b8b-5f57-4916-b9ed-c866017975de # Sidebar Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4d745e29-a2e8-47b5-a584-510330af7397: # Sidebar Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sidebarImage
    instructions: ''
    name: 'Sidebar Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:abfe2548-e0eb-46f4-b4f8-b5a54a315752' # Uploads
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:abfe2548-e0eb-46f4-b4f8-b5a54a315752' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  57d7fb75-9f65-4cb3-8af1-872b184c442c: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  58ac5a7f-03a6-4058-a3ea-97165e94a9fe: # Sidebar Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sidebarTitle
    instructions: ''
    name: 'Sidebar Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c1a37b8b-5f57-4916-b9ed-c866017975de: # Sidebar Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sidebarColour
    instructions: ''
    name: 'Sidebar Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - 'bg-light-main pad-300'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - 'bg-dark-main pad-300'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - 'bg-primary-main pad-300'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - 'bg-secondary-main pad-300'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - 'bg-tertiary-main pad-300'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - 'bg-quaternary-main pad-300'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ef9f9772-7ef7-46f7-bbd0-7a557f0231a5: # Text Area
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textArea
    instructions: ''
    name: 'Text Area'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
