field: 897bfff6-c7bf-4563-830e-72aaee559edc # Button Repeater
fieldLayouts:
  28221e33-7ae3-43b7-ae3e-38a717d1b47b:
    tabs:
      -
        elements:
          -
            fieldUid: 7a5062d1-d2a0-429f-b4a1-614469350044 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5d4e152e-2a40-4c1e-9dd9-3e8cd41a60ee # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1c8a2c40-4475-4830-8fc1-2e79ba75ab0a # Button Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1c8a2c40-4475-4830-8fc1-2e79ba75ab0a: # Button Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonColour
    instructions: ''
    name: 'Button Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Master
            -
              - value
              - master
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Inherit
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  5d4e152e-2a40-4c1e-9dd9-3e8cd41a60ee: # Button Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonStyle
    instructions: ''
    name: 'Button Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Ghost
            -
              - value
              - ghost
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - full-width
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7a5062d1-d2a0-429f-b4a1-614469350044: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        3: entry
        6: custom
        7: email
        8: tel
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: 'Read More'
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
