field: 978f9e16-6ec6-44d8-b080-bd4e834ff898 # Navigation
fieldLayouts:
  0f20152c-ac67-4a6d-8cfa-3de1064a5c00:
    tabs:
      -
        elements:
          -
            fieldUid: 0d7c0da2-090b-43d3-aa01-6cc0cd59be31 # Footer Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0d7c0da2-090b-43d3-aa01-6cc0cd59be31: # Footer Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: footerLink
    instructions: ''
    name: 'Footer Link'
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        3: entry
        6: custom
        7: email
        8: tel
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
