field: 74c51f77-ab75-4cce-8ce7-352fd188aaa8 # Block Padding
fieldLayouts:
  e148334c-7fd4-4bd2-bedb-c8b0a084b16c:
    tabs:
      -
        elements:
          -
            fieldUid: 2b46bac5-d65d-4430-8c70-e5f37d75440c # Padding Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 443d0186-8231-451d-85c9-b88daff3774f # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7d88ced8-47bd-467b-a723-b92a476b214f # Padding Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2498de96-42ec-4f5c-a42d-f5a11b31d6cd # Padding Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2b46bac5-d65d-4430-8c70-e5f37d75440c: # Padding Top
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingTop
    instructions: ''
    name: 'Padding Top'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-top-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - pad-top-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - pad-top-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-top-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-top-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-top-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-top-60
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-top-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7d88ced8-47bd-467b-a723-b92a476b214f: # Padding Left
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingLeft
    instructions: ''
    name: 'Padding Left'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-left-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - pad-left-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - pad-left-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-left-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-left-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-left-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-left-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-left-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  443d0186-8231-451d-85c9-b88daff3774f: # Padding Bottom
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingBottom
    instructions: ''
    name: 'Padding Bottom'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-bottom-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - pad-bottom-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - pad-bottom-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-bottom-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-bottom-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-bottom-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-bottom-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-bottom-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  2498de96-42ec-4f5c-a42d-f5a11b31d6cd: # Padding Right
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingRight
    instructions: ''
    name: 'Padding Right'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-right-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - pad-right-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - pad-right-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-right-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-right-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-right-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-right-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-right-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
