field: befa2684-fe20-4a12-a212-04049bf28030 # Block Padding
fieldLayouts:
  0d78163f-b121-4dab-8daa-9e4adac1de98:
    tabs:
      -
        elements:
          -
            fieldUid: 7a3f65fb-3554-4f3f-b79a-7077137e4cd1 # Padding Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb64d905-de20-4c73-8786-bdbcc448cb8f # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cd4d31c6-e857-4372-baa4-cc00ed90db22 # Padding Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2b97d88b-d400-42c7-9c91-fcdc45f5622f # Padding Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2b97d88b-d400-42c7-9c91-fcdc45f5622f: # Padding Right
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingRight
    instructions: ''
    name: 'Padding Right'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-right-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - pad-right-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - pad-right-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-right-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-right-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-right-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-right-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-right-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7a3f65fb-3554-4f3f-b79a-7077137e4cd1: # Padding Top
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingTop
    instructions: ''
    name: 'Padding Top'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-top-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - pad-top-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - pad-top-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-top-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-top-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-top-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-top-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-top-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  cd4d31c6-e857-4372-baa4-cc00ed90db22: # Padding Left
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingLeft
    instructions: ''
    name: 'Padding Left'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-left-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - pad-left-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - pad-left-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-left-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-left-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-left-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-left-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-left-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  eb64d905-de20-4c73-8786-bdbcc448cb8f: # Padding Bottom
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingBottom
    instructions: ''
    name: 'Padding Bottom'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-bottom-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - pad-bottom-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - pad-bottom-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-bottom-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-bottom-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-bottom-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-bottom-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-bottom-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
