field: f2977454-dd2b-45b3-8676-a55b00bcedbf # Block Padding
fieldLayouts:
  932f029e-a7cf-4e71-a5c4-cfd93b44dcb3:
    tabs:
      -
        elements:
          -
            fieldUid: a937c129-9c47-405b-ad82-7577b42bc164 # Padding Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e1bf351b-5521-420c-afb7-235ea64efb3a # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 20556a54-2e16-46f1-9cae-d4f3913a37b5 # Padding Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cd3d39f8-edaf-4ad2-a4d5-1a27ec8b3c57 # Padding Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  20556a54-2e16-46f1-9cae-d4f3913a37b5: # Padding Left
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingLeft
    instructions: ''
    name: 'Padding Left'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-left-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tiny
            -
              - value
              - pad-left-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-left-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-left-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-left-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-left-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-left-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a937c129-9c47-405b-ad82-7577b42bc164: # Padding Top
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingTop
    instructions: ''
    name: 'Padding Top'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-top-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tiny
            -
              - value
              - pad-top-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-top-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-top-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-top-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-top-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-top-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  cd3d39f8-edaf-4ad2-a4d5-1a27ec8b3c57: # Padding Right
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingRight
    instructions: ''
    name: 'Padding Right'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-right-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tiny
            -
              - value
              - pad-right-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-right-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-right-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-right-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-right-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-right-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e1bf351b-5521-420c-afb7-235ea64efb3a: # Padding Bottom
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingBottom
    instructions: ''
    name: 'Padding Bottom'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-bottom-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tiny
            -
              - value
              - pad-bottom-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-bottom-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-bottom-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-bottom-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-bottom-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-bottom-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
