field: 4b7ca3f9-a0f6-4ae5-b1ee-90146ff22231 # Block Padding
fieldLayouts:
  295a0f44-997c-4aa0-a230-b52170248cff:
    tabs:
      -
        elements:
          -
            fieldUid: f273dd40-b798-4727-9409-adc124794431 # Padding Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ed1ac0a4-a00a-4571-b335-52dd9943363f # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b858034-4677-4347-8edb-f513054d0938 # Padding Left
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c5af57ab-a295-46a1-b69d-cdac01cbb522 # Padding Right
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0b858034-4677-4347-8edb-f513054d0938: # Padding Left
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingLeft
    instructions: ''
    name: 'Padding Left'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - none
            -
              - value
              - pad-left-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tiny
            -
              - value
              - pad-left-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-left-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-left-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-left-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-left-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-left-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c5af57ab-a295-46a1-b69d-cdac01cbb522: # Padding Right
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingRight
    instructions: ''
    name: 'Padding Right'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-right-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tiny
            -
              - value
              - pad-right-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-right-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-right-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-right-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-right-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-right-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ed1ac0a4-a00a-4571-b335-52dd9943363f: # Padding Bottom
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingBottom
    instructions: ''
    name: 'Padding Bottom'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-bottom-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tiny
            -
              - value
              - pad-bottom-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-bottom-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-bottom-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-bottom-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-bottom-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-bottom-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f273dd40-b798-4727-9409-adc124794431: # Padding Top
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: paddingTop
    instructions: ''
    name: 'Padding Top'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - pad-top-000
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tiny
            -
              - value
              - pad-top-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - pad-top-300
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - pad-top-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - pad-top-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - pad-top-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - pad-top-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
