defaultPlacement: end
enableVersioning: true
handle: attractions
name: Attractions
propagationMethod: all
siteSettings:
  bfee3748-6727-406a-b769-74430862086f: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: attractions/_entry
    uriFormat: 'attractions/item/{slug}'
type: channel
