defaultPlacement: end
enableVersioning: true
handle: suppliers
name: Suppliers
propagationMethod: all
siteSettings:
  bfee3748-6727-406a-b769-74430862086f: # $SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
